## Доступные модели:
## Модели, доступные для использования: 'llama3.1:8b-instruct-q8_0', 'llama3.1:latest', 'gemma2:9b', 'mistral-nemo:12b'

Model: llama3.1:latest  # Указывает модель для использования. Если указано "All", будут загружены все доступные модели.
Questions: 'Default'    # Тип вопросов для использования из словаря вопросов, таких как 'Default' или 'All'.
Сhain_type: 'refine'    # Тип цепочки для обработки задач. "refine" используется здесь для уточнения ответа.
Temperature: 0.2        # Настройка температуры модели, которая влияет на случайность сгенерированного текста. Более низкие значения (0.1-0.3) делают ответы более детерминированными.
Embedding: sentence-transformers/all-MiniLM-L6-v2  # BAAI/bge-m3
Splitter:
  Type: 'character'     # Тип разбиения текста.
  Chunk_size: 4000      # Размер блока текста.
