version: '3.3'
services:
  web:
    build: .
    ports:
      - "9002:9002"
    environment:
      - STREAMLIT_SERVER_PORT=9002
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=true
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    volumes:
      - .:/app  # Для разработки
    restart: always
    network_mode: "host"  # Использование сети хоста для лучшей совместимости