services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - .:/app  # Для разработки

  # Добавьте другие сервисы (например, БД) при необходимости