embeddings: 
  type: huggingface
  name: BAAI/bge-m3  

vector_store:
  text_splitter:
    type: character
    chunk_size: 400
    separator: "\n" 
  type: default

model:
  type: chat-gpt
  name: gpt-4o
  temperature: 0.2
  max_tokens: 200

k:
  1