name: Update Version Badge from Commit

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on new tags matching vX.X.X
  workflow_dispatch: # Allows manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch the full history to ensure `git describe` works correctly

    - name: Get the latest tag version
      id: get_version
      run: |
        VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "Latest version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Update README with the new version badge
      run: |
        VERSION=${{ env.version }}
        BADGE_URL="https://img.shields.io/badge/version-${VERSION}-blue"
        sed -i "s|https://img.shields.io/badge/version-[^ ]*-blue|$BADGE_URL|g" README.md
        
    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git pull origin main
        git add README.md
        git commit -m "Update version badge to ${{ env.version }}"
        git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
